### ISSUE TITLE
Manual package list

### ISSUE THREAD

**Issue by hillalex** [HTAhackathon2024/HERA#2]
In the first instance, we will use a pre-defined list of known HE packages as an input to our data fetching script.

**Comment by hillalex** [comment]
`rdecision`: https://github.com/ajsims1704/rdecision

**Comment by hillalex** [comment]
All the packages here: https://r-hta.org/#resources

**Comment by alex-vand** [comment]
[BCEA](https://github.com/giabaio/BCEA)
[SAVI](https://github.com/Sheffield-Accelerated-VoI/SAVI)
[survHE](https://github.com/giabaio/survHE)
[flexsurv](https://github.com/chjackson/flexsurv)
[hesim](https://github.com/hesim-dev/hesim)
[heemod](https://github.com/pierucci/heemod)
[MAIC](https://github.com/Roche/Global-HTA-Evidence-Open/tree/master/Rpackages/MAIC)
[gemtcPlus](https://github.com/Roche/Global-HTA-Evidence-Open/tree/master/Rpackages/gemtcPlus)
[rpsftmPlus](https://github.com/Roche/Global-HTA-Evidence-Open/tree/master/Rpackages/rpsftmPlus)
[msm](https://github.com/chjackson/msm)
[mstate](https://www.gla.ac.uk/schools/healthwellbeing/research/hehta/cwilliams/)
[missingHE](https://github.com/AnGabrio/missingHE)
[EVSI](https://github.com/annaheath/EVSI)
[aldvmm](https://github.com/pletschm/aldvmm)
