### ISSUE TITLE
Create hexagon logo

### ISSUE THREAD

**Issue by bisacciamd** [HTAhackathon2024/HERA#34]

**Comment by carolinaheu** [comment]
![HERA_logo](https://github.com/user-attachments/assets/c04e0500-1e72-47cd-a060-34a41721edf2)
I crated a Logo, but am unsure whether to upload it to the images folder and then change the website code, or to remove the existing logo file and upload the new logo with the logo.png name....?

**Comment by bisacciamd** [comment]
Just delete the logo file - will be fine I suppose.
